# fly.toml app configuration file generated for teamtrack on 2024-01-01T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "teamtrack-grytt"
primary_region = "iad"

[build]

[env]
  DEBUG = "False"
  DJANGO_SETTINGS_MODULE = "teamtrack.settings_fly"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
