services:
  - type: web
    name: teamtrack
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: settings_render
    healthCheckPath: /attendance/

databases:
  - name: teamtrack-db
    plan: free
