services:
  # Bulletproof deployment configuration
  - type: web
    name: teamtrack
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: ./teamtrack/start_robust.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: settings_render
      - key: BASE_URL
        value: https://teamtrack-1.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: teamtrack-db
          property: connectionString
    healthCheckPath: /keep-alive/
    healthCheckGracePeriod: 600
    # CRITICAL: Link the database to this service
    databaseName: teamtrack-db

databases:
  - name: teamtrack-db
    plan: free
