# Generated by Django 5.0.7 on 2025-10-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.CharField(
                choices=[
                    ("PROJECT_MANAGER", "Project Manager"),
                    ("DESIGN", "Design"),
                    ("TECH", "Tech"),
                    ("PRODUCT_MANAGEMENT", "Product Management"),
                ],
                default="TECH",
                max_length=20,
            ),
        ),
    ]
