# Generated by Django 5.0.7 on 2025-10-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_role_user_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(
                choices=[
                    ("PROJECT_MANAGER", "Project Manager"),
                    ("DESIGN", "Design"),
                    ("TECH", "Tech"),
                    ("PRODUCT_MANAGEMENT", "Product Management"),
                    ("MARKETING", "Marketing"),
                ],
                default="TECH",
                max_length=20,
            ),
        ),
    ]
