# Generated by Django 5.2.7 on 2025-10-10 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("accounts", "0003_alter_user_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancerecord",
            name="marked_at",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="marked_by",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="present",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="session",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="user",
        ),
        migrations.DeleteModel(
            name="AttendanceSession",
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="date",
            field=models.DateField(default="2025-10-10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="member",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to="accounts.user"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(choices=[("Present", "Present"), ("Absent", "Absent"), ("Late", "Late")], default="Present", max_length=10),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("date", "member")},
        ),
    ]
