# Generated by Django 5.2.7 on 2025-10-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS attendance_attendancerecord;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE attendance_attendancerecord (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                date date NOT NULL,
                status varchar(10) NOT NULL,
                created_at datetime NOT NULL,
                updated_at datetime NOT NULL,
                member_id INTEGER NOT NULL REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED
            );
            """,
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            "CREATE UNIQUE INDEX attendance_attendancerecord_member_id_date_uniq ON attendance_attendancerecord (member_id, date);",
            reverse_sql="DROP INDEX IF EXISTS attendance_attendancerecord_member_id_date_uniq;"
        ),
    ]
