# Generated by Django 5.0.7 on 2025-10-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_team"),
    ]

    operations = []
