# Generated by Django 5.0.7 on 2025-10-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_updated_at_taskcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcomment",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Attach screenshots or files",
                null=True,
                upload_to="task_attachments/%Y/%m/%d/",
            ),
        ),
    ]
