# Generated by Django 5.0.7 on 2025-10-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="team",
            field=models.CharField(
                choices=[
                    ("PROJECT_MANAGER", "Project Manager"),
                    ("DESIGN", "Design"),
                    ("TECH", "Tech"),
                    ("PRODUCT_MANAGEMENT", "Product Management"),
                    ("MARKETING", "Marketing"),
                ],
                default="TECH",
                help_text="Team this task belongs to",
                max_length=20,
            ),
        ),
    ]
