# Generated by Django 5.2.7 on 2025-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_taskcomment_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("review", "Review"),
                    ("done", "Done"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="team",
            field=models.CharField(
                choices=[
                    ("development", "Development"),
                    ("design", "Design"),
                    ("marketing", "Marketing"),
                    ("sales", "Sales"),
                    ("support", "Support"),
                    ("management", "Management"),
                ],
                default="TECH",
                help_text="Team this task belongs to",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Attach screenshots or files",
                null=True,
                upload_to="task_attachments/",
            ),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="comment_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("update", "Update"),
                    ("note", "Note"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
    ]
