# Generated by Django 5.2.7 on 2025-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(
                choices=[
                    ("development", "Development"),
                    ("design", "Design"),
                    ("marketing", "Marketing"),
                    ("sales", "Sales"),
                    ("support", "Support"),
                    ("management", "Management"),
                ],
                default="TECH",
                max_length=20,
            ),
        ),
    ]
