# Generated by Django 5.2.7 on 2025-10-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={"ordering": ["-date", "member__username"]},
        ),
    ]
